//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebapiApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SMSCountry WebService", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/getInbox", ReplyAction="*")]
        WebapiApplication.ServiceReference1.getInboxResponse getInbox(WebapiApplication.ServiceReference1.getInboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/getInbox", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.getInboxResponse> getInboxAsync(WebapiApplication.ServiceReference1.getInboxRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/MarkRead_inbox", ReplyAction="*")]
        WebapiApplication.ServiceReference1.MarkRead_inboxResponse MarkRead_inbox(WebapiApplication.ServiceReference1.MarkRead_inboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/MarkRead_inbox", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.MarkRead_inboxResponse> MarkRead_inboxAsync(WebapiApplication.ServiceReference1.MarkRead_inboxRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Mark_UnRead_inbox", ReplyAction="*")]
        WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponse Mark_UnRead_inbox(WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Mark_UnRead_inbox", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponse> Mark_UnRead_inboxAsync(WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendTextSMS", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendTextSMSResponse SendTextSMS(WebapiApplication.ServiceReference1.SendTextSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendTextSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendTextSMSResponse> SendTextSMSAsync(WebapiApplication.ServiceReference1.SendTextSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendUnicodeSMS", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendUnicodeSMSResponse SendUnicodeSMS(WebapiApplication.ServiceReference1.SendUnicodeSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendUnicodeSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendUnicodeSMSResponse> SendUnicodeSMSAsync(WebapiApplication.ServiceReference1.SendUnicodeSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendPictureSMS", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendPictureSMSResponse SendPictureSMS(WebapiApplication.ServiceReference1.SendPictureSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendPictureSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendPictureSMSResponse> SendPictureSMSAsync(WebapiApplication.ServiceReference1.SendPictureSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendBinarySMS", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendBinarySMSResponse SendBinarySMS(WebapiApplication.ServiceReference1.SendBinarySMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendBinarySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendBinarySMSResponse> SendBinarySMSAsync(WebapiApplication.ServiceReference1.SendBinarySMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendRingTone", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendRingToneResponse SendRingTone(WebapiApplication.ServiceReference1.SendRingToneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendRingTone", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendRingToneResponse> SendRingToneAsync(WebapiApplication.ServiceReference1.SendRingToneRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendLOGO", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendLOGOResponse SendLOGO(WebapiApplication.ServiceReference1.SendLOGORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendLOGO", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendLOGOResponse> SendLOGOAsync(WebapiApplication.ServiceReference1.SendLOGORequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendWapPush", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendWapPushResponse SendWapPush(WebapiApplication.ServiceReference1.SendWapPushRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendWapPush", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendWapPushResponse> SendWapPushAsync(WebapiApplication.ServiceReference1.SendWapPushRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendFlashSMS", ReplyAction="*")]
        WebapiApplication.ServiceReference1.SendFlashSMSResponse SendFlashSMS(WebapiApplication.ServiceReference1.SendFlashSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendFlashSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendFlashSMSResponse> SendFlashSMSAsync(WebapiApplication.ServiceReference1.SendFlashSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Getbalance", ReplyAction="*")]
        WebapiApplication.ServiceReference1.GetbalanceResponse Getbalance(WebapiApplication.ServiceReference1.GetbalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Getbalance", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.GetbalanceResponse> GetbalanceAsync(WebapiApplication.ServiceReference1.GetbalanceRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/GetDeliveryReport", ReplyAction="*")]
        WebapiApplication.ServiceReference1.GetDeliveryReportResponse GetDeliveryReport(WebapiApplication.ServiceReference1.GetDeliveryReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/GetDeliveryReport", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.GetDeliveryReportResponse> GetDeliveryReportAsync(WebapiApplication.ServiceReference1.GetDeliveryReportRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/sendMultiSMS", ReplyAction="*")]
        WebapiApplication.ServiceReference1.sendMultiSMSResponse sendMultiSMS(WebapiApplication.ServiceReference1.sendMultiSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/sendMultiSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.sendMultiSMSResponse> sendMultiSMSAsync(WebapiApplication.ServiceReference1.sendMultiSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInbox", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.getInboxRequestBody Body;
        
        public getInboxRequest() {
        }
        
        public getInboxRequest(WebapiApplication.ServiceReference1.getInboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class getInboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToDate;
        
        public getInboxRequestBody() {
        }
        
        public getInboxRequestBody(string username, string password, string FromDate, string ToDate) {
            this.username = username;
            this.password = password;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.getInboxResponseBody Body;
        
        public getInboxResponse() {
        }
        
        public getInboxResponse(WebapiApplication.ServiceReference1.getInboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class getInboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInboxResult;
        
        public getInboxResponseBody() {
        }
        
        public getInboxResponseBody(string getInboxResult) {
            this.getInboxResult = getInboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkRead_inboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkRead_inbox", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.MarkRead_inboxRequestBody Body;
        
        public MarkRead_inboxRequest() {
        }
        
        public MarkRead_inboxRequest(WebapiApplication.ServiceReference1.MarkRead_inboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class MarkRead_inboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgid;
        
        public MarkRead_inboxRequestBody() {
        }
        
        public MarkRead_inboxRequestBody(string username, string password, int msgid) {
            this.username = username;
            this.password = password;
            this.msgid = msgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkRead_inboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkRead_inboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.MarkRead_inboxResponseBody Body;
        
        public MarkRead_inboxResponse() {
        }
        
        public MarkRead_inboxResponse(WebapiApplication.ServiceReference1.MarkRead_inboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class MarkRead_inboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarkRead_inboxResult;
        
        public MarkRead_inboxResponseBody() {
        }
        
        public MarkRead_inboxResponseBody(string MarkRead_inboxResult) {
            this.MarkRead_inboxResult = MarkRead_inboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mark_UnRead_inboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mark_UnRead_inbox", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequestBody Body;
        
        public Mark_UnRead_inboxRequest() {
        }
        
        public Mark_UnRead_inboxRequest(WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class Mark_UnRead_inboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgid;
        
        public Mark_UnRead_inboxRequestBody() {
        }
        
        public Mark_UnRead_inboxRequestBody(string username, string password, int msgid) {
            this.username = username;
            this.password = password;
            this.msgid = msgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mark_UnRead_inboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mark_UnRead_inboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponseBody Body;
        
        public Mark_UnRead_inboxResponse() {
        }
        
        public Mark_UnRead_inboxResponse(WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class Mark_UnRead_inboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mark_UnRead_inboxResult;
        
        public Mark_UnRead_inboxResponseBody() {
        }
        
        public Mark_UnRead_inboxResponseBody(string Mark_UnRead_inboxResult) {
            this.Mark_UnRead_inboxResult = Mark_UnRead_inboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextSMS", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendTextSMSRequestBody Body;
        
        public SendTextSMSRequest() {
        }
        
        public SendTextSMSRequest(WebapiApplication.ServiceReference1.SendTextSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendTextSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderID;
        
        public SendTextSMSRequestBody() {
        }
        
        public SendTextSMSRequestBody(string username, string password, string mobilenumbers, string message, string senderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.senderID = senderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendTextSMSResponseBody Body;
        
        public SendTextSMSResponse() {
        }
        
        public SendTextSMSResponse(WebapiApplication.ServiceReference1.SendTextSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendTextSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendTextSMSResult;
        
        public SendTextSMSResponseBody() {
        }
        
        public SendTextSMSResponseBody(string SendTextSMSResult) {
            this.SendTextSMSResult = SendTextSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicodeSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicodeSMS", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendUnicodeSMSRequestBody Body;
        
        public SendUnicodeSMSRequest() {
        }
        
        public SendUnicodeSMSRequest(WebapiApplication.ServiceReference1.SendUnicodeSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendUnicodeSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderID;
        
        public SendUnicodeSMSRequestBody() {
        }
        
        public SendUnicodeSMSRequestBody(string username, string password, string mobilenumbers, string message, string senderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.senderID = senderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicodeSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicodeSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendUnicodeSMSResponseBody Body;
        
        public SendUnicodeSMSResponse() {
        }
        
        public SendUnicodeSMSResponse(WebapiApplication.ServiceReference1.SendUnicodeSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendUnicodeSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendUnicodeSMSResult;
        
        public SendUnicodeSMSResponseBody() {
        }
        
        public SendUnicodeSMSResponseBody(string SendUnicodeSMSResult) {
            this.SendUnicodeSMSResult = SendUnicodeSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPictureSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPictureSMS", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendPictureSMSRequestBody Body;
        
        public SendPictureSMSRequest() {
        }
        
        public SendPictureSMSRequest(WebapiApplication.ServiceReference1.SendPictureSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendPictureSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendPictureSMSRequestBody() {
        }
        
        public SendPictureSMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPictureSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPictureSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendPictureSMSResponseBody Body;
        
        public SendPictureSMSResponse() {
        }
        
        public SendPictureSMSResponse(WebapiApplication.ServiceReference1.SendPictureSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendPictureSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendPictureSMSResult;
        
        public SendPictureSMSResponseBody() {
        }
        
        public SendPictureSMSResponseBody(string SendPictureSMSResult) {
            this.SendPictureSMSResult = SendPictureSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBinarySMS", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendBinarySMSRequestBody Body;
        
        public SendBinarySMSRequest() {
        }
        
        public SendBinarySMSRequest(WebapiApplication.ServiceReference1.SendBinarySMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendBinarySMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendBinarySMSRequestBody() {
        }
        
        public SendBinarySMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBinarySMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendBinarySMSResponseBody Body;
        
        public SendBinarySMSResponse() {
        }
        
        public SendBinarySMSResponse(WebapiApplication.ServiceReference1.SendBinarySMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendBinarySMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendBinarySMSResult;
        
        public SendBinarySMSResponseBody() {
        }
        
        public SendBinarySMSResponseBody(string SendBinarySMSResult) {
            this.SendBinarySMSResult = SendBinarySMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRingToneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRingTone", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendRingToneRequestBody Body;
        
        public SendRingToneRequest() {
        }
        
        public SendRingToneRequest(WebapiApplication.ServiceReference1.SendRingToneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendRingToneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendRingToneRequestBody() {
        }
        
        public SendRingToneRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRingToneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRingToneResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendRingToneResponseBody Body;
        
        public SendRingToneResponse() {
        }
        
        public SendRingToneResponse(WebapiApplication.ServiceReference1.SendRingToneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendRingToneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendRingToneResult;
        
        public SendRingToneResponseBody() {
        }
        
        public SendRingToneResponseBody(string SendRingToneResult) {
            this.SendRingToneResult = SendRingToneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLOGORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLOGO", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendLOGORequestBody Body;
        
        public SendLOGORequest() {
        }
        
        public SendLOGORequest(WebapiApplication.ServiceReference1.SendLOGORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendLOGORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendLOGORequestBody() {
        }
        
        public SendLOGORequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLOGOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLOGOResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendLOGOResponseBody Body;
        
        public SendLOGOResponse() {
        }
        
        public SendLOGOResponse(WebapiApplication.ServiceReference1.SendLOGOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendLOGOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendLOGOResult;
        
        public SendLOGOResponseBody() {
        }
        
        public SendLOGOResponseBody(string SendLOGOResult) {
            this.SendLOGOResult = SendLOGOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPush", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendWapPushRequestBody Body;
        
        public SendWapPushRequest() {
        }
        
        public SendWapPushRequest(WebapiApplication.ServiceReference1.SendWapPushRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendWapPushRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WapUrl;
        
        public SendWapPushRequestBody() {
        }
        
        public SendWapPushRequestBody(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
            this.WapUrl = WapUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPushResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendWapPushResponseBody Body;
        
        public SendWapPushResponse() {
        }
        
        public SendWapPushResponse(WebapiApplication.ServiceReference1.SendWapPushResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendWapPushResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWapPushResult;
        
        public SendWapPushResponseBody() {
        }
        
        public SendWapPushResponseBody(string SendWapPushResult) {
            this.SendWapPushResult = SendWapPushResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFlashSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFlashSMS", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendFlashSMSRequestBody Body;
        
        public SendFlashSMSRequest() {
        }
        
        public SendFlashSMSRequest(WebapiApplication.ServiceReference1.SendFlashSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendFlashSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendFlashSMSRequestBody() {
        }
        
        public SendFlashSMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFlashSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFlashSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.SendFlashSMSResponseBody Body;
        
        public SendFlashSMSResponse() {
        }
        
        public SendFlashSMSResponse(WebapiApplication.ServiceReference1.SendFlashSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendFlashSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendFlashSMSResult;
        
        public SendFlashSMSResponseBody() {
        }
        
        public SendFlashSMSResponseBody(string SendFlashSMSResult) {
            this.SendFlashSMSResult = SendFlashSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getbalance", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.GetbalanceRequestBody Body;
        
        public GetbalanceRequest() {
        }
        
        public GetbalanceRequest(WebapiApplication.ServiceReference1.GetbalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetbalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetbalanceRequestBody() {
        }
        
        public GetbalanceRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetbalanceResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.GetbalanceResponseBody Body;
        
        public GetbalanceResponse() {
        }
        
        public GetbalanceResponse(WebapiApplication.ServiceReference1.GetbalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetbalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetbalanceResult;
        
        public GetbalanceResponseBody() {
        }
        
        public GetbalanceResponseBody(string GetbalanceResult) {
            this.GetbalanceResult = GetbalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryReport", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.GetDeliveryReportRequestBody Body;
        
        public GetDeliveryReportRequest() {
        }
        
        public GetDeliveryReportRequest(WebapiApplication.ServiceReference1.GetDeliveryReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetDeliveryReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong SMS_Job_No;
        
        public GetDeliveryReportRequestBody() {
        }
        
        public GetDeliveryReportRequestBody(string username, string password, ulong SMS_Job_No) {
            this.username = username;
            this.password = password;
            this.SMS_Job_No = SMS_Job_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryReportResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.GetDeliveryReportResponseBody Body;
        
        public GetDeliveryReportResponse() {
        }
        
        public GetDeliveryReportResponse(WebapiApplication.ServiceReference1.GetDeliveryReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetDeliveryReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeliveryReportResult;
        
        public GetDeliveryReportResponseBody() {
        }
        
        public GetDeliveryReportResponseBody(string GetDeliveryReportResult) {
            this.GetDeliveryReportResult = GetDeliveryReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultiSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMultiSMS", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.sendMultiSMSRequestBody Body;
        
        public sendMultiSMSRequest() {
        }
        
        public sendMultiSMSRequest(WebapiApplication.ServiceReference1.sendMultiSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class sendMultiSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MNO_MSG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public char dr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string wapurl;
        
        public sendMultiSMSRequestBody() {
        }
        
        public sendMultiSMSRequestBody(string user, string password, string MNO_MSG, string sid, string mtype, char dr, string wapurl) {
            this.user = user;
            this.password = password;
            this.MNO_MSG = MNO_MSG;
            this.sid = sid;
            this.mtype = mtype;
            this.dr = dr;
            this.wapurl = wapurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultiSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMultiSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public WebapiApplication.ServiceReference1.sendMultiSMSResponseBody Body;
        
        public sendMultiSMSResponse() {
        }
        
        public sendMultiSMSResponse(WebapiApplication.ServiceReference1.sendMultiSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class sendMultiSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMultiSMSResult;
        
        public sendMultiSMSResponseBody() {
        }
        
        public sendMultiSMSResponseBody(string sendMultiSMSResult) {
            this.sendMultiSMSResult = sendMultiSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WebapiApplication.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WebapiApplication.ServiceReference1.ServiceSoap>, WebapiApplication.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.getInboxResponse WebapiApplication.ServiceReference1.ServiceSoap.getInbox(WebapiApplication.ServiceReference1.getInboxRequest request) {
            return base.Channel.getInbox(request);
        }
        
        public string getInbox(string username, string password, string FromDate, string ToDate) {
            WebapiApplication.ServiceReference1.getInboxRequest inValue = new WebapiApplication.ServiceReference1.getInboxRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.getInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            WebapiApplication.ServiceReference1.getInboxResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).getInbox(inValue);
            return retVal.Body.getInboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.getInboxResponse> WebapiApplication.ServiceReference1.ServiceSoap.getInboxAsync(WebapiApplication.ServiceReference1.getInboxRequest request) {
            return base.Channel.getInboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.getInboxResponse> getInboxAsync(string username, string password, string FromDate, string ToDate) {
            WebapiApplication.ServiceReference1.getInboxRequest inValue = new WebapiApplication.ServiceReference1.getInboxRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.getInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).getInboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.MarkRead_inboxResponse WebapiApplication.ServiceReference1.ServiceSoap.MarkRead_inbox(WebapiApplication.ServiceReference1.MarkRead_inboxRequest request) {
            return base.Channel.MarkRead_inbox(request);
        }
        
        public string MarkRead_inbox(string username, string password, int msgid) {
            WebapiApplication.ServiceReference1.MarkRead_inboxRequest inValue = new WebapiApplication.ServiceReference1.MarkRead_inboxRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.MarkRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            WebapiApplication.ServiceReference1.MarkRead_inboxResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).MarkRead_inbox(inValue);
            return retVal.Body.MarkRead_inboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.MarkRead_inboxResponse> WebapiApplication.ServiceReference1.ServiceSoap.MarkRead_inboxAsync(WebapiApplication.ServiceReference1.MarkRead_inboxRequest request) {
            return base.Channel.MarkRead_inboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.MarkRead_inboxResponse> MarkRead_inboxAsync(string username, string password, int msgid) {
            WebapiApplication.ServiceReference1.MarkRead_inboxRequest inValue = new WebapiApplication.ServiceReference1.MarkRead_inboxRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.MarkRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).MarkRead_inboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponse WebapiApplication.ServiceReference1.ServiceSoap.Mark_UnRead_inbox(WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest request) {
            return base.Channel.Mark_UnRead_inbox(request);
        }
        
        public string Mark_UnRead_inbox(string username, string password, int msgid) {
            WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest inValue = new WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).Mark_UnRead_inbox(inValue);
            return retVal.Body.Mark_UnRead_inboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponse> WebapiApplication.ServiceReference1.ServiceSoap.Mark_UnRead_inboxAsync(WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest request) {
            return base.Channel.Mark_UnRead_inboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.Mark_UnRead_inboxResponse> Mark_UnRead_inboxAsync(string username, string password, int msgid) {
            WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest inValue = new WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.Mark_UnRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).Mark_UnRead_inboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendTextSMSResponse WebapiApplication.ServiceReference1.ServiceSoap.SendTextSMS(WebapiApplication.ServiceReference1.SendTextSMSRequest request) {
            return base.Channel.SendTextSMS(request);
        }
        
        public string SendTextSMS(string username, string password, string mobilenumbers, string message, string senderID) {
            WebapiApplication.ServiceReference1.SendTextSMSRequest inValue = new WebapiApplication.ServiceReference1.SendTextSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendTextSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            WebapiApplication.ServiceReference1.SendTextSMSResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendTextSMS(inValue);
            return retVal.Body.SendTextSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendTextSMSResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendTextSMSAsync(WebapiApplication.ServiceReference1.SendTextSMSRequest request) {
            return base.Channel.SendTextSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendTextSMSResponse> SendTextSMSAsync(string username, string password, string mobilenumbers, string message, string senderID) {
            WebapiApplication.ServiceReference1.SendTextSMSRequest inValue = new WebapiApplication.ServiceReference1.SendTextSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendTextSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendTextSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendUnicodeSMSResponse WebapiApplication.ServiceReference1.ServiceSoap.SendUnicodeSMS(WebapiApplication.ServiceReference1.SendUnicodeSMSRequest request) {
            return base.Channel.SendUnicodeSMS(request);
        }
        
        public string SendUnicodeSMS(string username, string password, string mobilenumbers, string message, string senderID) {
            WebapiApplication.ServiceReference1.SendUnicodeSMSRequest inValue = new WebapiApplication.ServiceReference1.SendUnicodeSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendUnicodeSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            WebapiApplication.ServiceReference1.SendUnicodeSMSResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendUnicodeSMS(inValue);
            return retVal.Body.SendUnicodeSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendUnicodeSMSResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendUnicodeSMSAsync(WebapiApplication.ServiceReference1.SendUnicodeSMSRequest request) {
            return base.Channel.SendUnicodeSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendUnicodeSMSResponse> SendUnicodeSMSAsync(string username, string password, string mobilenumbers, string message, string senderID) {
            WebapiApplication.ServiceReference1.SendUnicodeSMSRequest inValue = new WebapiApplication.ServiceReference1.SendUnicodeSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendUnicodeSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendUnicodeSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendPictureSMSResponse WebapiApplication.ServiceReference1.ServiceSoap.SendPictureSMS(WebapiApplication.ServiceReference1.SendPictureSMSRequest request) {
            return base.Channel.SendPictureSMS(request);
        }
        
        public string SendPictureSMS(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendPictureSMSRequest inValue = new WebapiApplication.ServiceReference1.SendPictureSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendPictureSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            WebapiApplication.ServiceReference1.SendPictureSMSResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendPictureSMS(inValue);
            return retVal.Body.SendPictureSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendPictureSMSResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendPictureSMSAsync(WebapiApplication.ServiceReference1.SendPictureSMSRequest request) {
            return base.Channel.SendPictureSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendPictureSMSResponse> SendPictureSMSAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendPictureSMSRequest inValue = new WebapiApplication.ServiceReference1.SendPictureSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendPictureSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendPictureSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendBinarySMSResponse WebapiApplication.ServiceReference1.ServiceSoap.SendBinarySMS(WebapiApplication.ServiceReference1.SendBinarySMSRequest request) {
            return base.Channel.SendBinarySMS(request);
        }
        
        public string SendBinarySMS(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendBinarySMSRequest inValue = new WebapiApplication.ServiceReference1.SendBinarySMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendBinarySMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            WebapiApplication.ServiceReference1.SendBinarySMSResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendBinarySMS(inValue);
            return retVal.Body.SendBinarySMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendBinarySMSResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendBinarySMSAsync(WebapiApplication.ServiceReference1.SendBinarySMSRequest request) {
            return base.Channel.SendBinarySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendBinarySMSResponse> SendBinarySMSAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendBinarySMSRequest inValue = new WebapiApplication.ServiceReference1.SendBinarySMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendBinarySMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendBinarySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendRingToneResponse WebapiApplication.ServiceReference1.ServiceSoap.SendRingTone(WebapiApplication.ServiceReference1.SendRingToneRequest request) {
            return base.Channel.SendRingTone(request);
        }
        
        public string SendRingTone(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendRingToneRequest inValue = new WebapiApplication.ServiceReference1.SendRingToneRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendRingToneRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            WebapiApplication.ServiceReference1.SendRingToneResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendRingTone(inValue);
            return retVal.Body.SendRingToneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendRingToneResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendRingToneAsync(WebapiApplication.ServiceReference1.SendRingToneRequest request) {
            return base.Channel.SendRingToneAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendRingToneResponse> SendRingToneAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendRingToneRequest inValue = new WebapiApplication.ServiceReference1.SendRingToneRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendRingToneRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendRingToneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendLOGOResponse WebapiApplication.ServiceReference1.ServiceSoap.SendLOGO(WebapiApplication.ServiceReference1.SendLOGORequest request) {
            return base.Channel.SendLOGO(request);
        }
        
        public string SendLOGO(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendLOGORequest inValue = new WebapiApplication.ServiceReference1.SendLOGORequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendLOGORequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            WebapiApplication.ServiceReference1.SendLOGOResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendLOGO(inValue);
            return retVal.Body.SendLOGOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendLOGOResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendLOGOAsync(WebapiApplication.ServiceReference1.SendLOGORequest request) {
            return base.Channel.SendLOGOAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendLOGOResponse> SendLOGOAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendLOGORequest inValue = new WebapiApplication.ServiceReference1.SendLOGORequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendLOGORequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendLOGOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendWapPushResponse WebapiApplication.ServiceReference1.ServiceSoap.SendWapPush(WebapiApplication.ServiceReference1.SendWapPushRequest request) {
            return base.Channel.SendWapPush(request);
        }
        
        public string SendWapPush(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl) {
            WebapiApplication.ServiceReference1.SendWapPushRequest inValue = new WebapiApplication.ServiceReference1.SendWapPushRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendWapPushRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            inValue.Body.WapUrl = WapUrl;
            WebapiApplication.ServiceReference1.SendWapPushResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendWapPush(inValue);
            return retVal.Body.SendWapPushResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendWapPushResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendWapPushAsync(WebapiApplication.ServiceReference1.SendWapPushRequest request) {
            return base.Channel.SendWapPushAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendWapPushResponse> SendWapPushAsync(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl) {
            WebapiApplication.ServiceReference1.SendWapPushRequest inValue = new WebapiApplication.ServiceReference1.SendWapPushRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendWapPushRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            inValue.Body.WapUrl = WapUrl;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendWapPushAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.SendFlashSMSResponse WebapiApplication.ServiceReference1.ServiceSoap.SendFlashSMS(WebapiApplication.ServiceReference1.SendFlashSMSRequest request) {
            return base.Channel.SendFlashSMS(request);
        }
        
        public string SendFlashSMS(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendFlashSMSRequest inValue = new WebapiApplication.ServiceReference1.SendFlashSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendFlashSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            WebapiApplication.ServiceReference1.SendFlashSMSResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendFlashSMS(inValue);
            return retVal.Body.SendFlashSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendFlashSMSResponse> WebapiApplication.ServiceReference1.ServiceSoap.SendFlashSMSAsync(WebapiApplication.ServiceReference1.SendFlashSMSRequest request) {
            return base.Channel.SendFlashSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.SendFlashSMSResponse> SendFlashSMSAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            WebapiApplication.ServiceReference1.SendFlashSMSRequest inValue = new WebapiApplication.ServiceReference1.SendFlashSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.SendFlashSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).SendFlashSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.GetbalanceResponse WebapiApplication.ServiceReference1.ServiceSoap.Getbalance(WebapiApplication.ServiceReference1.GetbalanceRequest request) {
            return base.Channel.Getbalance(request);
        }
        
        public string Getbalance(string username, string password) {
            WebapiApplication.ServiceReference1.GetbalanceRequest inValue = new WebapiApplication.ServiceReference1.GetbalanceRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.GetbalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebapiApplication.ServiceReference1.GetbalanceResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).Getbalance(inValue);
            return retVal.Body.GetbalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.GetbalanceResponse> WebapiApplication.ServiceReference1.ServiceSoap.GetbalanceAsync(WebapiApplication.ServiceReference1.GetbalanceRequest request) {
            return base.Channel.GetbalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.GetbalanceResponse> GetbalanceAsync(string username, string password) {
            WebapiApplication.ServiceReference1.GetbalanceRequest inValue = new WebapiApplication.ServiceReference1.GetbalanceRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.GetbalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).GetbalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.GetDeliveryReportResponse WebapiApplication.ServiceReference1.ServiceSoap.GetDeliveryReport(WebapiApplication.ServiceReference1.GetDeliveryReportRequest request) {
            return base.Channel.GetDeliveryReport(request);
        }
        
        public string GetDeliveryReport(string username, string password, ulong SMS_Job_No) {
            WebapiApplication.ServiceReference1.GetDeliveryReportRequest inValue = new WebapiApplication.ServiceReference1.GetDeliveryReportRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.GetDeliveryReportRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.SMS_Job_No = SMS_Job_No;
            WebapiApplication.ServiceReference1.GetDeliveryReportResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).GetDeliveryReport(inValue);
            return retVal.Body.GetDeliveryReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.GetDeliveryReportResponse> WebapiApplication.ServiceReference1.ServiceSoap.GetDeliveryReportAsync(WebapiApplication.ServiceReference1.GetDeliveryReportRequest request) {
            return base.Channel.GetDeliveryReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.GetDeliveryReportResponse> GetDeliveryReportAsync(string username, string password, ulong SMS_Job_No) {
            WebapiApplication.ServiceReference1.GetDeliveryReportRequest inValue = new WebapiApplication.ServiceReference1.GetDeliveryReportRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.GetDeliveryReportRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.SMS_Job_No = SMS_Job_No;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).GetDeliveryReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebapiApplication.ServiceReference1.sendMultiSMSResponse WebapiApplication.ServiceReference1.ServiceSoap.sendMultiSMS(WebapiApplication.ServiceReference1.sendMultiSMSRequest request) {
            return base.Channel.sendMultiSMS(request);
        }
        
        public string sendMultiSMS(string user, string password, string MNO_MSG, string sid, string mtype, char dr, string wapurl) {
            WebapiApplication.ServiceReference1.sendMultiSMSRequest inValue = new WebapiApplication.ServiceReference1.sendMultiSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.sendMultiSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.MNO_MSG = MNO_MSG;
            inValue.Body.sid = sid;
            inValue.Body.mtype = mtype;
            inValue.Body.dr = dr;
            inValue.Body.wapurl = wapurl;
            WebapiApplication.ServiceReference1.sendMultiSMSResponse retVal = ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).sendMultiSMS(inValue);
            return retVal.Body.sendMultiSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.sendMultiSMSResponse> WebapiApplication.ServiceReference1.ServiceSoap.sendMultiSMSAsync(WebapiApplication.ServiceReference1.sendMultiSMSRequest request) {
            return base.Channel.sendMultiSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebapiApplication.ServiceReference1.sendMultiSMSResponse> sendMultiSMSAsync(string user, string password, string MNO_MSG, string sid, string mtype, char dr, string wapurl) {
            WebapiApplication.ServiceReference1.sendMultiSMSRequest inValue = new WebapiApplication.ServiceReference1.sendMultiSMSRequest();
            inValue.Body = new WebapiApplication.ServiceReference1.sendMultiSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.MNO_MSG = MNO_MSG;
            inValue.Body.sid = sid;
            inValue.Body.mtype = mtype;
            inValue.Body.dr = dr;
            inValue.Body.wapurl = wapurl;
            return ((WebapiApplication.ServiceReference1.ServiceSoap)(this)).sendMultiSMSAsync(inValue);
        }
    }
}
